source "https://rubygems.org"

gem "ruby_llm"
gem "sqlite3"
gem "sqlite-vec"
gem "neighbor"
gem "thor"
gem "tty-prompt"
gem "tty-spinner"
gem "tty-markdown"
gem "dotenv"
gem "zeitwerk"
gem "pdf-reader"
gem "activesupport"
gem "activerecord"
gem "diff-lcs"
gem "pastel"
gem "reline"
